#!/usr/bin/env bash
# Render static-site build step.
#
# Generates config.js from the API_BASE_URL environment variable so the
# deployed UI points at the backend service rather than at localhost. The
# blueprint wires API_BASE_URL from the backend service's host, so it is
# always set on Render.
#
# Fails the build when API_BASE_URL is missing: shipping a UI that silently
# calls localhost is worse than not shipping it.

set -euo pipefail

if [ -z "${API_BASE_URL:-}" ]; then
  echo "ERROR: API_BASE_URL is not set." >&2
  echo "Set it to the backend service origin, e.g. https://keyword-analyzer-api.onrender.com" >&2
  exit 1
fi

# Strip any trailing slash; app.js joins paths with a leading slash.
BASE="${API_BASE_URL%/}"

# Accept a bare hostname (Render's `fromService: property: host` yields one)
# and promote it to a full https:// origin.
case "$BASE" in
  http://*|https://*) ;;
  *) BASE="https://${BASE}" ;;
esac

cat > config.js <<CONFIG
/* Generated by build.sh at deploy time. Do not edit. */
window.APP_CONFIG = {
  API_BASE_URL: "${BASE}"
};
CONFIG

echo "Built config.js with API_BASE_URL=${BASE}"
